# Generated by Django 4.0.10 on 2023-12-21 08:15

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=pathlib.PurePosixPath('/code/static_files/default/default_profile_picture.svg'), null=True, upload_to='profile_pics/'),
        ),
    ]
