# Generated by Django 4.0.10 on 2023-12-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_interest_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='image',
            field=models.FileField(default='interests_covers/default_interest_covers.svg', upload_to='interests_covers/'),
        ),
    ]
