# Generated by Django 4.0.10 on 2023-12-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_interest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.interest'),
        ),
    ]
