# Generated by Django 4.0.10 on 2023-12-28 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='relation_formats',
            field=models.CharField(choices=[('Hunter', 'Want to have some good time'), ('Love', 'Want to find real love'), ('Friend', 'Searching friends'), ('SE', 'Something Else')], default='ns', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UploadedProfilePictures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('profile_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_main_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.uploadedprofilepictures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_uploaded_pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='profiles.uploadedprofilepictures'),
        ),
    ]
