# Generated by Django 4.0.10 on 2023-12-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_uploaded_pictures',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_uploaded_pictures',
            field=models.ManyToManyField(blank=True, null=True, related_name='uploader', to='profiles.uploadedprofilepictures'),
        ),
    ]
