# Generated by Django 4.0.10 on 2023-12-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='additional_profile',
        ),
    ]
