# Generated by Django 4.0.10 on 2023-12-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_rename_sender_notification_additional_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='Notification text', max_length=512),
        ),
    ]
