# Generated by Django 4.0.10 on 2023-12-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_main_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.uploadedprofilepictures'),
        ),
    ]
