version: '3.9'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-t%mj%nth)%okky7$$4ss%d(^y)^m#lp8+dbhtg_1t_*sn&l)=fv"
      - 'DJANGO_DEBUG=True'
  redis:
    image: redis
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
  postgres_data:
