# Generated by Django 4.0.10 on 2024-01-08 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('REASON1', '1111111111111'), ('REASON2', '22222222'), ('REASON3', '333333333')], max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responsible_moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complains_responsible', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_complains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
