# Generated by Django 4.0.10 on 2024-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
