# Generated by Django 4.0.10 on 2024-01-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderating', '0002_complain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='decision',
            field=models.BooleanField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complain',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
