# Generated by Django 4.0.10 on 2024-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderating', '0003_complain_decision_complain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
