# Generated by Django 4.0.10 on 2024-01-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderating', '0004_alter_complain_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='status',
        ),
    ]
