# Generated by Django 4.0.10 on 2024-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderating', '0005_remove_complain_decision_remove_complain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='decision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='complain',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
