# Generated by Django 4.0.10 on 2024-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_locationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationprofile',
            name='longitude',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
