# Generated by Django 4.0.10 on 2023-12-20 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('like', '0002_alter_match_profile1_alter_match_profile2_likemodel'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='like.match')),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile1', to='profiles.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile2', to='profiles.profile')),
            ],
        ),
    ]
