# Generated by Django 4.0.10 on 2023-12-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_alter_match_profile1_alter_match_profile2_likemodel'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='match',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='like.match'),
        ),
    ]
