# Generated by Django 4.0.10 on 2023-12-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_interests'),
        ('chats', '0003_alter_chat_created_at_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='profile1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='profile2',
        ),
        migrations.AddField(
            model_name='chat',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chat'),
        ),
    ]
