# Generated by Django 4.0.10 on 2023-12-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_interests'),
        ('like', '0002_alter_match_profile1_alter_match_profile2_likemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likemodel',
            old_name='liked_ad',
            new_name='liked_at',
        ),
        migrations.AddField(
            model_name='match',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DislikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_dislikes', to='profiles.profile')),
            ],
        ),
    ]
